name: PR Guidelines Comment

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - 'dependabot/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: 'Comment about PR review guidelines'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR --body-file .github/workflows/pr_guidelines_comment_body.txt
